use_frameworks!

#source 'https://github.com/bukalapak/BukalapakiOSSpecs'
target 'SampleLib_Example' do
#    pod 'SampleLib'
  pod 'SampleLib', :path => '../'

#  target 'SampleLib_Tests' do
#    inherit! :search_paths

    
#  end
end
